/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EventManager } from "./EventManager";
export * as factories from "./factories";
export { EventManager__factory } from "./factories/EventManager__factory";
